### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by danieldietsch** [pief/authhttp#8]
I am using Dokuwiki  2023-04-04a "Jack Jackrum" with authsplit, the latest HTTP Authentication Plugin and PHP 8.1.20.
Although it seems to be working, I get log errors for each page visit:
``` log
2023-09-01 09:44:14     .../lib/plugins/authhttp/auth.php(35)        E_WARNING: Undefined variable $conf
  #0 .../lib/plugins/authhttp/auth.php(35): dokuwiki\ErrorHandler::errorHandler()
  #1 .../inc/load.php(156): require('...')
  #2 [internal function]: load_autoload()
  #3 .../inc/Extension/PluginController.php(107): class_exists()
  #4 .../inc/pluginutils.php(54): dokuwiki\Extension\PluginController->load()
  #5 .../lib/plugins/authsplit/auth.php(51): plugin_load()
  #6 .../inc/Extension/PluginController.php(131): auth_plugin_authsplit->__construct()
  #7 .../inc/auth.php(47): dokuwiki\Extension\PluginController->load()
  #8 .../inc/init.php(232): auth_setup()
  #9 .../lib/exe/taskrunner.php(12): require_once('...')
  #10 {main}
2023-09-01 09:44:14     .../lib/plugins/authhttp/auth.php(35)        E_WARNING: Trying to access array offset on value of type null
  #0 .../lib/plugins/authhttp/auth.php(35): dokuwiki\ErrorHandler::errorHandler()
  #1 .../inc/load.php(156): require('...')
  #2 [internal function]: load_autoload()
  #3 .../inc/Extension/PluginController.php(107): class_exists()
  #4 .../inc/pluginutils.php(54): dokuwiki\Extension\PluginController->load()
  #5 .../lib/plugins/authsplit/auth.php(51): plugin_load()
  #6 .../inc/Extension/PluginController.php(131): auth_plugin_authsplit->__construct()
  #7 .../inc/auth.php(47): dokuwiki\Extension\PluginController->load()
  #8 .../inc/init.php(232): auth_setup()
  #9 .../lib/exe/taskrunner.php(12): require_once('...')
  #10 {main}
2023-09-01 09:44:14     .../lib/plugins/authhttp/auth.php(80)        E_WARNING: Undefined variable $active
  #0 .../lib/plugins/authhttp/auth.php(80): dokuwiki\ErrorHandler::errorHandler()
  #1 .../inc/Extension/PluginController.php(131): auth_plugin_authhttp->__construct()
  #2 .../inc/pluginutils.php(54): dokuwiki\Extension\PluginController->load()
  #3 .../lib/plugins/authsplit/auth.php(51): plugin_load()
  #4 .../inc/Extension/PluginController.php(131): auth_plugin_authsplit->__construct()
  #5 .../inc/auth.php(47): dokuwiki\Extension\PluginController->load()
  #6 .../inc/init.php(232): auth_setup()
  #7 .../lib/exe/taskrunner.php(12): require_once('...')
  #8 {main}
```
These errors startet after migrating from PHP 7.4 to 8.1.

**Comment by danieldietsch** [comment]
Perfect, just tried it and the warnings are gone.

Thank you!
